#ifndef KPENGINE_RUNTIME_GRAPHICS_TYPE_H
#define KPENGINE_RUNTIME_GRAPHICS_TYPE_H

#include <cstdint>

enum class TextureFormat
{
    TEXTURE_FORMAT_UNKNOW,
    TEXTURE_FORMAT_R8_UNORM,
    TEXTURE_FORMAT_R8_SRGB,
    TEXTURE_FORMAT_RG8_UNORM,
    TEXTURE_FORMAT_RG8_SRGB,
    TEXTURE_FORMAT_RGB8_UNORM,
    TEXTURE_FORMAT_RGB8_SRGB,
    TEXTURE_FORMAT_RGBA8_UNORM,
    TEXTURE_FORMAT_RGBA8_SRGB,
    TEXTURE_FORMAT_D24S8,
    TEXTURE_FORMAT_D32
};

enum class ShaderStage : uint8_t
{
    SHADER_STAGE_UNKNOW,
    SHADER_STAGE_VERTEX,
    SHADER_STAGE_FRAGMENT,
    SHADER_STAGE_GEOMETRY,
    SHADER_STAGE_COMPUTE
};

#endif